// <auto-generated />
using System;
using InventorySaaSBackend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace inventorysaasbackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620022211_AddCategoriaActivo")]
    partial class AddCategoriaActivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventario")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventorySaaSBackend.Domain.Entity.UnidadMedida", b =>
                {
                    b.Property<Guid>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_unidad")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("abreviatura");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdUnidad");

                    b.HasIndex("IdEmpresa", "Nombre")
                        .IsUnique();

                    b.ToTable("Unidades", "inventario");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Almacenes", b =>
                {
                    b.Property<Guid>("IdAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_almacen")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdAlmacen");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Almacenes", "inventario");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Categoria", b =>
                {
                    b.Property<Guid>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_categoria")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdEmpresa", "Nombre")
                        .IsUnique();

                    b.ToTable("Categorias", "inventario");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Empresas", b =>
                {
                    b.Property<Guid>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("Nombre");

                    b.ToTable("Empresas", "shared");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Movimientos", b =>
                {
                    b.Property<Guid>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_movimiento")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IdAlmacen")
                        .HasColumnType("uuid")
                        .HasColumnName("id_almacen");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_producto");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("Fecha");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdProducto");

                    b.HasIndex("Tipo");

                    b.ToTable("Movimientos", "inventario");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Productos", b =>
                {
                    b.Property<Guid>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_producto")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<bool>("Agotado86")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("agotado_86");

                    b.Property<string>("Estacion")
                        .HasColumnType("text")
                        .HasColumnName("estacion");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uuid")
                        .HasColumnName("id_categoria");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<Guid?>("IdUnidad")
                        .HasColumnType("uuid")
                        .HasColumnName("id_unidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_venta");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.HasKey("IdProducto");

                    b.HasIndex("Activo");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUnidad");

                    b.HasIndex("IdEmpresa", "Sku")
                        .IsUnique();

                    b.ToTable("Productos", "inventario");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Stock", b =>
                {
                    b.Property<Guid>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_stock")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cantidad");

                    b.Property<Guid>("IdAlmacen")
                        .HasColumnType("uuid")
                        .HasColumnName("id_almacen");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_producto");

                    b.HasKey("IdStock");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdProducto", "IdAlmacen")
                        .IsUnique();

                    b.ToTable("Stock", "inventario", t =>
                        {
                            t.HasCheckConstraint("CK_Stock_Cantidad", "cantidad >= 0");
                        });
                });

            modelBuilder.Entity("InventorySaaSBackend.Domain.Entity.UnidadMedida", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Almacenes", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Categoria", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Movimientos", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Almacenes", null)
                        .WithMany()
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Models.Productos", null)
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Productos", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Domain.Entity.UnidadMedida", null)
                        .WithMany()
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Stock", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Almacenes", null)
                        .WithMany()
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Models.Productos", null)
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
