// <auto-generated />
using System;
using InventorySaaSBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventorySaaS_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventorySaaSBackend.Models.Almacenes", b =>
                {
                    b.Property<int>("IdAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_almacen");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAlmacen"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdAlmacen");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdEmpresa", "Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Empresas", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("Nombre");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Movimientos", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("integer")
                        .HasColumnName("id_almacen");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("Fecha");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdProducto");

                    b.HasIndex("Tipo");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Productos", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.HasKey("IdProducto");

                    b.HasIndex("Activo");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEmpresa", "Sku")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Stock", b =>
                {
                    b.Property<int>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_stock");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStock"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cantidad");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("integer")
                        .HasColumnName("id_almacen");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("id_producto");

                    b.HasKey("IdStock");

                    b.HasIndex("IdAlmacen");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdProducto", "IdAlmacen")
                        .IsUnique();

                    b.ToTable("Stock", t =>
                        {
                            t.HasCheckConstraint("CK_Stock_Cantidad", "cantidad >= 0");
                        });
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Almacenes", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Categoria", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Movimientos", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Almacenes", null)
                        .WithMany()
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Models.Productos", null)
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Productos", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InventorySaaSBackend.Models.Stock", b =>
                {
                    b.HasOne("InventorySaaSBackend.Models.Almacenes", null)
                        .WithMany()
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Models.Empresas", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventorySaaSBackend.Models.Productos", null)
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
